### PR TITLE
Fix: Return empty content for multipart requests to match PHP-FPM behavior

### LINKED ISSUE #68: RequestConverter — Multipart form-data raw body exposed via getContent(), inconsistent with PHP-FPM
## Problem Description

For `multipart/form-data` requests, the converter passes `$rawRequest->rawBody()` as the `$content` parameter to Symfony's Request constructor. This means `$request->getContent()` returns the raw multipart body (including file contents). Under PHP-FPM, `php://input` is empty for multipart requests — PHP consumes the body during `$_POST`/`$_FILES` parsing.

## Location

`src/DTO/RequestConverter.php`, line 29

### PHP-FPM behavior

From the PHP manual:
> `php://input` is not available with `enctype="multipart/form-data"`.

Under PHP-FPM, `$request->getContent()` returns `""` for multipart requests.

### Current converter behavior

```php
$request = new Request(
    ...
    content: $rawRequest->rawBody(),  // Raw multipart body with file contents
);
```

For a multipart request uploading a 10MB file, `$rawRequest->rawBody()` contains the entire 10MB body. This is stored in `$request->content` — meaning the file data exists in memory twice (once in the content string, once in the temp file created by Workerman).

### Impact

1. **Memory usage** — file data stored twice in memory. A 50MB upload consumes ~100MB.
2. **Data exposure** — code that logs `$request->getContent()` will log raw file contents.
3. **Behavioral inconsistency** — code tested under PHP-FPM that expects `getContent()` to be empty for multipart will behave differently under Workerman.

### When this does NOT matter

- Most Symfony applications never call `getContent()` on multipart requests
- File access goes through `$request->files`, which works correctly

## Proposed Solution

Detect multipart content type and pass empty content:

```php
$contentType = $rawRequest->header('content-type', '');
$isMultipart = stripos($contentType, 'multipart/form-data') !== false;

$request = new Request(
    ...
    content: $isMultipart ? '' : $rawRequest->rawBody(),
);
```

## Priority

🟡 **LOW** — does not affect typical application behavior. Primarily a memory optimization and consistency improvement.

## Tests

```php
// Multipart request
$this->assertSame('', $symfonyRequest->getContent());
$this->assertNotNull($symfonyRequest->files->get('file'));

// JSON request — body preserved
$this->assertSame('{"key":"value"}', $symfonyRequest->getContent());

// Form-urlencoded — body preserved
$this->assertSame('key=value', $symfonyRequest->getContent());
```

### PR DESCRIPTION
**Pull request by s2x**
## Summary

For multipart/form-data requests, `getContent()` now returns empty string to match PHP-FPM behavior where `php://input` is not available.

### Changes

- Modified `RequestConverter::toSymfonyRequest()` to pass empty content for multipart requests
- Improved content-type detection using `stripos()` instead of `preg_match()`
- Added 3 new tests for content behavior across different content types

### Benefits

- Prevents duplicate memory usage (file data was stored twice in memory)
- Prevents data exposure via logging `getContent()`
- Consistent behavior with PHP-FPM

## Testing

- All 25 RequestConverter tests pass
- Tests cover multipart, JSON, and form-urlencoded content types

Closes #68

### CODE REVIEW

File: src/DTO/RequestConverter.php [hunk 1]
```diff
@@ -23,7 +23,9 @@ public static function toSymfonyRequest(\Workerman\Protocols\Http\Request $rawRe
         // Only populate POST bag for form-encoded content types
         // JSON and other content types should leave POST bag empty (like PHP-FPM)
         $contentType = $rawRequest->header('content-type', '');
-        $isFormData = preg_match('/^(application\/x-www-form-urlencoded|multipart\/form-data)\b/i', (string) $contentType);
+        $isFormUrlEncoded = stripos((string) $contentType, 'application/x-www-form-urlencoded') !== false;
```
Comment (s2x) [inline src/DTO/RequestConverter.php]: **[Suggestion]** `stripos()` matches the substring anywhere in the string, whereas the original `preg_match` used `^` (start anchor) and `\b` (word boundary). In practice false positives are extremely unlikely, but this is a behavioral regression from stricter to looser matching.

Consider using `str_starts_with()` to preserve the original anchored behavior:

```suggestion
        $ct = strtolower((string) $rawRequest->header('content-type', ''));
        $isFormUrlEncoded = str_starts_with($ct, 'application/x-www-form-urlencoded');
        $isMultipart = str_starts_with($ct, 'multipart/form-data');
```

_— coder-model via Qwen Code /review_

File: src/DTO/RequestConverter.php [hunk 2]
```diff
@@ -69,14 +71,18 @@ public static function toSymfonyRequest(\Workerman\Protocols\Http\Request $rawRe
             }
         }
 
+        // For multipart requests, pass empty content to match PHP-FPM behavior
+        // (php://input is not available for multipart - body is consumed during $_POST/$_FILES parsing)
+        $content = $isMultipart ? '' : $rawRequest->rawBody();
```
Comment (s2x) [inline src/DTO/RequestConverter.php:76]: **[Suggestion]** Before this change, `getContent()` on a multipart request returned the full raw body. Now it returns `''`. Any application code, middleware, or custom parser reading raw multipart data will silently break.

The behavior is correct for PHP-FPM compatibility, but this should be documented as a **breaking change** in `CHANGELOG.md` with a migration note so existing users are aware.

_— coder-model via Qwen Code /review_
