### PR TITLE
fix: RequestConverter — Missing Nested File Handling (closes #26)

### LINKED ISSUE #26: RequestConverter — Missing Nested File Handling
# RequestConverter — Missing Nested File Handling

## Problem Description

In `src/DTO/RequestConverter.php:39-45`, only flat file uploads are handled. Forms with `files[0]`, `files[avatar]`, or `<input name="documents[]" multiple>` do not work.

## Location

`src/DTO/RequestConverter.php`, lines 39-45

## Analysis

Current code:
```php
foreach ($rawRequest->file() ?? [] as $key => $value) {
    $type = $value['type'] ?? 'application/octet-stream';
    $request->files->set(
        $key,
        new UploadedFile($value['tmp_name'], $value['name'], $type === '' ? 'application/octet-stream' : $type),
    );
}
```

Workerman returns nested arrays for forms with multiple files. The current code assumes each element has direct keys `tmp_name`, `name`, `type`.

## Proposed Solution

Add recursive file processing:
```php
private static function processFiles(array $files): array
{
    $result = [];
    foreach ($files as $key => $value) {
        if (isset($value['tmp_name'])) {
            $type = $value['type'] ?? 'application/octet-stream';
            $result[$key] = new UploadedFile(
                $value['tmp_name'],
                $value['name'],
                $type === '' ? 'application/octet-stream' : $type,
            );
        } elseif (is_array($value)) {
            $result[$key] = self::processFiles($value);
        }
    }
    return $result;
}
```

## Priority

🟠 **HIGH** — forms with multiple files do not work.

## Tests

Test with nested file structure (multiple file input, named file arrays).

### PR DESCRIPTION
**Pull request by s2x**
## Problem

The `RequestConverter` previously only handled flat file uploads. HTML forms with nested file arrays (e.g., `files[]`, `documents[0]`, or `<input name="documents[]" multiple>`) would fail because Workerman returns nested arrays for multi-file forms, but the existing code assumed every array element directly contained `tmp_name`, `name`, and `type` keys.

## Solution

Added a recursive `processFiles()` method that properly parses nested file structures and converts them to `UploadedFile` objects for Symfony Request.

### Changes

- **`src/DTO/RequestConverter.php`**: Added `processFiles()` method that recursively converts `$_FILES`-style arrays to `UploadedFile` objects
- **`tests/RequestConverterTest.php`**: Added 3 new test cases:
  - `testNestedFileArrayWithMultipleFiles` — indexed file arrays
  - `testDeeplyNestedAssociativeFileArray` — nested associative structures
  - `testMultipleFileInputsWithNumericKeys` — files with numeric keys

All 268 tests pass, PHPStan/PHP-CS-Fixer/Rector clean.

Closes #26.

### CODE REVIEW

File: src/DTO/RequestConverter.php [hunk 1]
```diff
@@ -85,4 +89,42 @@ public static function toSymfonyRequest(\Workerman\Protocols\Http\Request $rawRe
...
+     * @param array<string, mixed> $files
+     *
+     * @return array<string, mixed>
+     */
+    private static function processFiles(array $files): array
+    {
+        $result = [];
+        foreach ($files as $key => $value) {
+            if (is_array($value)) {
+                // Check if this is a single file structure (has 'tmp_name' key)
```
Comment (s2x) [inline src/DTO/RequestConverter.php:108]: **[Suggestion]** `isset($value['tmp_name'])` returns `false` when the key exists but is `null`, which is inconsistent with `FileUploadValidator::validateSingleFileArray()` that uses `array_key_exists()`. If Workerman ever returns `['tmp_name' => null, ...]`, the validator passes but `processFiles()` falls into the recursion branch and silently drops the file.

```suggestion
                if (array_key_exists('tmp_name', $value)) {
```

_— coder-model via Qwen Code /review_
