### PR TITLE
fix: KernelFactory — Singleton Kernel Without State Reset (closes #22)

### LINKED ISSUE #22: KernelFactory — Singleton Kernel Without State Reset Between Requests
# KernelFactory — Singleton Kernel Without State Reset Between Requests

## Problem Description

The Symfony Kernel is created once and cached in `KernelFactory`. In `SymfonyController`, `boot()` is called for every request, but `shutdown()` is never called. Services are not reset between requests.

## Location

`src/KernelFactory.php:20-31`, `src/Middleware/SymfonyController.php:31`

## Analysis

In a long-running process, the Symfony kernel is not designed to handle multiple requests without reset. Problems:
- EntityManager accumulates entities in the identity map
- Request-scoped services persist between requests
- Memory leaks from accumulated state
- `terminate()` is called (line 43), but `shutdown()` is not

Symfony provides the `kernel.reset` tag and `ResetInterface` mechanism for resetting services, but the bundle doesn't use it.

## Proposed Solution

After `terminate()`, call service reset:
```php
if ($this->kernel->getContainer()->has('services_resetter')) {
    $this->kernel->getContainer()->get('services_resetter')->reset();
}
```

Alternatively, document that users should use `AlwaysRebootStrategy` or `MemoryRebootStrategy` for applications with state.

## Priority

🟠 **HIGH** — memory leaks and stale state in long-running processes.

## Tests

Integration test executing two requests and verifying service state reset.

### PR DESCRIPTION
**Pull request by s2x**
## Summary
- Adds services_resetter call after kernel->terminate() to reset services between requests
- Prevents memory leaks and stale state in long-running processes (EntityManager identity map, request-scoped services)
- Gracefully handles missing services_resetter (test mocks, minimal configs)

## Changes
- `src/Middleware/SymfonyController.php` - Added `resetServices()` method called after terminate
- `tests/SymfonyControllerTest.php` - Added tests for service reset functionality

## Testing
- All 265 tests pass (11 skipped for Symfony version compatibility)
- Tests verify:
  - Services reset is called when services_resetter is available
  - No errors when services_resetter is not available (backward compatible)

### CODE REVIEW

File: src/Middleware/SymfonyController.php [hunk 1]
```diff
@@ -59,10 +60,24 @@ public function terminateIfNeeded(): void
...
                 $this->symfonyRequest = null;
                 $this->symfonyResponse = null;
             }
         }
     }
+
+    private function resetServices(): void
+    {
+        try {
+            $container = $this->kernel->getContainer();
```
Comment (s2x) [inline src/Middleware/SymfonyController.php]: **[Suggestion]** Double container lookup (`has()` + `get()`) on the hot path — `resetServices()` performs two separate service-locator lookups per request:

```php
$container->has('services_resetter')  // first lookup
$container->get('services_resetter')  // second lookup
```

Since the presence of `services_resetter` is a **static property of the application's service configuration** (it never changes between requests), this double-lookup repeats unnecessary work on every single request.

In a high-throughput Workerman server, caching the `services_resetter` reference after the first lookup would eliminate this per-request overhead. For example, cache the resolved `ResetInterface` (or `null` if unavailable) in a private property after the first call:

```php
private ?ResetInterface $servicesResetter = null;
private bool $servicesResetterInitialized = false;

private function resetServices(): void
{
    if (!$this->servicesResetterInitialized) {
        try {
            $container = $this->kernel->getContainer();
            if ($container->has('services_resetter')) {
                $resetter = $container->get('services_resetter');
                if ($resetter instanceof ResetInterface) {
                    $this->servicesResetter = $resetter;
                }
            }
        } catch (\Throwable) {
            // log or handle
        }
        $this->servicesResetterInitialized = true;
    }
    $this->servicesResetter?->reset();
}
```

_— coder-model via Qwen Code /review_

File: src/Middleware/SymfonyController.php [hunk 2]
```diff
@@ -59,10 +60,24 @@ public function terminateIfNeeded(): void
...
+            if ($container->has('services_resetter')) {
+                $servicesResetter = $container->get('services_resetter');
+                if ($servicesResetter instanceof ResetInterface) {
+                    $servicesResetter->reset();
+                }
+            }
+        } catch (\Throwable) {
```
Comment (s2x) [inline src/Middleware/SymfonyController.php]: **[Suggestion]** `catch (\Throwable)` silently swallows **all** exceptions, including `Error` subclasses — with an empty body, there is zero observability into reset failures.

This is problematic because:

1. **Contradicts the PR's goal.** The PR aims to prevent memory leaks in long-running processes. But if the container is in an inconsistent state or the resetter throws, the failure is invisible — services never get reset, and memory leaks accumulate with no trace.
2. **No debugging trail.** If `getContainer()` returns something unexpected, or `has()`/`get()` throws for a reason other than service absence, the failure disappears completely.
3. **Asymmetric error handling.** The `HttpRequestHandler` wraps `terminateIfNeeded()` in try-catch with `error_log()` — but because `resetServices()` absorbs its own exceptions, reset failures never reach that logging.

**Recommended fix** — at minimum, log the exception:

```php
} catch (\Throwable $e) {
    error_log(sprintf(
        '[workerman-bundle] Failed to reset services: %s in %s:%d',
        $e->getMessage(),
        $e->getFile(),
        $e->getLine(),
    ));
}
```

**Alternative** — narrow the catch to `ContainerExceptionInterface` and re-throw other exceptions, letting the caller's existing error handling take over. This ensures structural errors (e.g., container API misuse) are not silently ignored.

_— coder-model via Qwen Code /review_

File: tests/SymfonyControllerTest.php [hunk 3]
```diff
@@ -24,6 +25,7 @@ final class TestTerminableKernel implements KernelInterface, TerminableInterface
     public bool $bootCalled = false;
     public bool $terminateCalled = false;
     public int $terminateCount = 0;
+    public bool $servicesResetCalled = false;
```
Comment (s2x) [inline tests/SymfonyControllerTest.php]: **[Suggestion]** `TestTerminableKernel::$servicesResetCalled` is dead code — the property is declared but never written to or asserted.

`TestTerminableKernel::getContainer()` throws `RuntimeException('Not implemented')`, which `resetServices()` silently catches. So `$servicesResetCalled` stays `false` forever. The property appears to have been copied from `TestKernelWithServicesResetter`, but it serves no purpose here.

**Fix:** Remove `public bool $servicesResetCalled = false;` from `TestTerminableKernel` to avoid misleading readers.

_— coder-model via Qwen Code /review_

File: tests/SymfonyControllerTest.php [hunk 4]
```diff
@@ -846,4 +1032,46 @@ public function getRemotePort(): int
...
+        $this->assertFalse($kernel->terminateCalled, 'Terminate should not be called during __invoke');
+        $this->assertFalse($kernel->servicesResetCalled, 'Services reset should not be called during __invoke');
+
+        $controller->terminateIfNeeded();
+
+        $this->assertTrue($kernel->terminateCalled, 'Terminate should be called after terminateIfNeeded');
+        $this->assertTrue($kernel->servicesResetCalled, 'Services reset should be called after terminateIfNeeded');
+    }
+
+    public function testTerminateIfNeededDoesNotCallServicesResetterWhenNotAvailable(): void
```
Comment (s2x) [inline tests/SymfonyControllerTest.php]: **[Suggestion]** `testTerminateIfNeededDoesNotCallServicesResetterWhenNotAvailable` doesn't actually test the 'service unavailable' path.

The test uses `TestTerminableKernel`, whose `getContainer()` throws `RuntimeException('Not implemented')`. The test passes because `resetServices()` swallows the exception — but the assertion only verifies `$kernel->terminateCalled`. The test never reaches the `has('services_resetter')` check; it only verifies that exception-swallowing works.

This gives **false confidence** that the 'service not available' branch is correct. If the exception-handling behavior were ever changed (e.g., per the logging suggestion above), this test would fail unexpectedly.

**Fix:** Use a kernel mock whose `getContainer()` returns a container where `has('services_resetter')` returns `false`. This exercises the actual availability check rather than an exception path. Alternatively, rename the test to reflect what it actually verifies.

_— coder-model via Qwen Code /review_

**Review by s2x — COMMENTED** [review]
Most previous suggestions have been addressed — great work on adding caching, logging, and cleaning up test code! 🎉

One remaining issue: `$servicesResetterInitialized` is set to `true` even when resolution fails (line 87). If `getContainer()` throws on the first request, the flag is permanently `true` and `reset()` is never called for the lifetime of the worker process.

File: src/Middleware/SymfonyController.php [hunk 5]
```diff
@@ -59,10 +64,40 @@ public function terminateIfNeeded(): void
...
+                $container = $this->kernel->getContainer();
+                if ($container->has('services_resetter')) {
+                    $resetter = $container->get('services_resetter');
+                    if ($resetter instanceof ResetInterface) {
+                        $this->servicesResetter = $resetter;
+                    }
+                }
+            } catch (\Throwable $e) {
+                $this->logger?->error(
+                    'Failed to resolve services_resetter',
```
Comment (s2x) [inline src/Middleware/SymfonyController.php:89]: **[Suggestion]** `$servicesResetterInitialized = true` is set unconditionally — even when an exception is caught. If `getContainer()` throws on the first request (transient failure), the flag is permanently `true` and `reset()` is never called for the lifetime of the worker process.

```suggestion
            $this->servicesResetterInitialized = true;
```

**Fix:** Only set the flag when we have a definitive answer:
- If `has()` returns false → set `true` (definitively no resetter)
- If `has()` returns true and we got a valid `ResetInterface` → set `true`
- If an exception occurs → do NOT set `true`, so the next request retries

This way a transient container failure doesn't permanently disable service resets.

**Comment by s2x** [comment]
## Code Review Fixes

Changes applied during code review:

### 1. PHPStan type annotations in test mocks
- **`tests/SymfonyControllerTest.php`** — Added `@return array<string, mixed>|bool|float|int|string|\\UnitEnum|null` to `getParameter()` methods in both anonymous `ContainerInterface` mock classes. This satisfies PHPStan level 8's requirement for value types in iterable `array`.
- **`phpstan.neon.dist`** — Removed the `ignoreErrors` entry that was previously used to suppress this issue. No longer needed.

### 2. Container access in `KernelFactory.php`
- **`src/KernelFactory.php`** — Fixed logger resolution in the `catch` block of `resetServices()`. Changed `->has('logger')` / `->get('logger')` to `->has('logger')` / `->get('logger')`. `KernelInterface` does not define `has()` or `get()` methods — these belong to `ContainerInterface`.

### 3. Risky test fix
- **`tests/KernelFactoryTest.php`** — Removed `->assertTrue(true)` (no-op assertion) and replaced it with `->expects($this->never())->method('get')` to properly assert that `get()` is not called when `services_resetter` is absent.

File: src/Middleware/SymfonyController.php [hunk 6]
```diff
@@ -59,10 +64,40 @@ public function terminateIfNeeded(): void
...
+                    ['exception' => $e->getMessage(), 'file' => $e->getFile(), 'line' => $e->getLine()],
+                );
+            }
+            $this->servicesResetterInitialized = true;
```
Comment (s2x) [inline src/Middleware/SymfonyController.php]: **[Critical]** `$servicesResetterInitialized = true` is set unconditionally after the catch block. If `getContainer()` throws on the first request, the flag is permanently `true` and `reset()` is NEVER called for the lifetime of the worker.

This was flagged in the previous review round and remains unfixed. A single transient failure becomes a permanent silent failure.

**Fix:** Move `$this->servicesResetterInitialized = true` inside the `try` block (set it when `has()` returns a definitive answer), and do NOT set it in the `catch` — so the next request retries:

```php
try {
    $container = $this->kernel->getContainer();
    if ($container->has('services_resetter')) {
        $resetter = $container->get('services_resetter');
        if ($resetter instanceof ResetInterface) {
            $this->servicesResetter = $resetter;
        }
    }
    // Definitive answer: either resetter exists or doesn't
    $this->servicesResetterInitialized = true;
} catch (\Throwable $e) {
    $this->logger?->error(
        'Failed to resolve services_resetter',
        ['exception' => $e],
    );
    // Do NOT set initialized — retry next request
}
```

_— coder-model via Qwen Code /review_

**Review by s2x — COMMENTED** [review]
Most previous suggestions addressed well (caching, logging, PHPStan types) ✅. One critical issue remains unfixed from the previous review round — see inline comment.

File: src/Middleware/SymfonyController.php (hunk 5 above)
Comment (s2x) [inline src/Middleware/SymfonyController.php:89]: **[Suggestion]** PSR-3 loggers expect `'exception' => $e` (the Throwable object), not `$e->getMessage()` (a string). Passing the Throwable preserves the full stack trace and exception chain.

```suggestion
                ['exception' => $e],
```

Same fix applies to the second error log (line 97-100).

_— coder-model via Qwen Code /review_

**Comment by s2x** [comment]
**[Critical — detailed explanation]** The problem is that `$servicesResetterInitialized = true` (line 91) sits **outside** the `try/catch`, which means it executes regardless of whether the resolution succeeded or failed.

Here's the exact failure scenario:

1. **Request #1 arrives** → `resetServices()` is called
2. `$servicesResetterInitialized` is `false` → enters the resolution block
3. `$this->kernel->getContainer()` **throws** an exception (e.g., container not ready, race condition during boot)
4. `catch` block logs the error ✓
5. **BUT** `$servicesResetterInitialized = true` still executes (line 91)
6. `$servicesResetter` is still `null`

Now for **every subsequent request (#2, #3, ... #1000000)**:
- `if (!$this->servicesResetterInitialized)` → **false** (already true)
- Resolution is never retried
- `$this->servicesResetter?->reset()` → no-op on `null`
- Services are **never reset** for the lifetime of this worker process

In Workerman, a single controller instance handles thousands of requests. One transient error on the first request permanently disables service reset — EntityManager identity maps grow forever, request-scoped services leak, memory grows until the worker crashes.

**The fix** — move `$this->servicesResetterInitialized = true` inside the `try` block, so it only executes when we got a definitive answer:

```php
if (!$this->servicesResetterInitialized) {
    try {
        $container = $this->kernel->getContainer();
        if ($container->has('services_resetter')) {
            $resetter = $container->get('services_resetter');
            if ($resetter instanceof ResetInterface) {
                $this->servicesResetter = $resetter;
            }
        }
        // We got a definitive answer: resetter exists or doesn't
        $this->servicesResetterInitialized = true;
    } catch (\Throwable $e) {
        $this->logger?->error(
            'Failed to resolve services_resetter',
            ['exception' => $e],
        );
        // Do NOT set initialized → next request will retry
    }
}
```

_— coder-model via Qwen Code /review_

**Review by s2x — COMMENTED** [review]
Critical issue fixed — `$servicesResetterInitialized` moved inside `try` block, transient failures will now be retried. All tests pass. LGTM! ✅

_— coder-model via Qwen Code /review_
